output:
    folder: './outputs/CNN/test'
    sub: 'run'

training:
    epochs: 200
    workers: 15
    callbacks:
        ckpt_loss:
            filepath: '<OUTPUTDIR>/checkpoints/best_loss'
            monitor: 'val_loss'
            save_weights_only: True
            save_best_only: True
        ckpt_roc:
            filepath: '<OUTPUTDIR>/checkpoints/best_roc'
            monitor: 'val_roc_auc'
            save_weights_only: True
            save_best_only: True
        tensor_board:
            log_dir: '<OUTPUTDIR>/tb_logs' 
            histogram_freq: 50
        scheduler:
            type: 'const'
            learning_rate: 0.0001
data:
    general:
        batch_size: 16
        image_size: [112, 112, 48]
        bundle_size: [126, 126, 48]
        image_path: './data/image_data/image_files.h5'
        rescale:
            input_range: [-250., 250]
            output_range: [0., 255.]
    train:
        df_path: './data/patient_data/train.csv' 
        bundles_path: './data/bundles/three_dim/train.h5' 
        weight_dict: {0: 2.08, 1: 0.66} # OPC + HNSCC 
        training: True
        augment:
            flip: True
            rot: True
    valid:
        df_path: './data/patient_data/valid.csv' 
        bundles_path: './data/bundles/three_dim/valid.h5' 
        weight_dict: {0: 2.37, 1: 0.63} # HN PET CT
        training: False
        augment:
            flip: False
            rot: False

model:
    size:
        input_size: [112, 112, 48, 1]
        output_size: 1

        conv_filters: [16, 32, 32, 64, [128, 128]]
        pool_kernel: [[2, 2, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]] 
        pool_stride: [[2, 2, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]] 
        conv_kernel: [3, 3, 3]
        conv_drop: [False, False, False, False, [False, 0.25]]
        conv_bn: False

        dense_units: [256, 128]
        dense_drop: [0.25, 0.25]
        dense_bn: False

        activation: 'relu'
        out_activation: 'sigmoid'

    optimizer:
        name: 'adam'

    loss:
        type: 'binary_crossentropy'
